modLoader = "kotlinforforge"
loaderVersion = "[5,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
    modId = "btpos-devutil"
    version = "${version}"
    displayName = "${mod_name}"
    authors = ""
    description = '''
${mod_desc}
'''
#logoFile = ""

[[dependencies.btpos-devutil]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.btpos-devutil]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.8,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.btpos-devutil]]
    modId = "architectury"
    type = "required"
    versionRange = "[17.0.8,)"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
    config = "btpos-devutil.mixins.json"
